create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 20),
  score integer not null check (score between 0 and 1000000),
  runs_completed smallint not null check (runs_completed between 0 and 5),
  outcome text not null check (outcome in ('flow_blocked', 'mission_complete')),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_scores_ranking_idx
  on public.leaderboard_scores (score desc, created_at asc);

alter table public.leaderboard_scores enable row level security;

create policy "Anyone can view leaderboard scores"
  on public.leaderboard_scores
  for select
  to anon, authenticated
  using (true);

create policy "Anyone can submit a leaderboard score"
  on public.leaderboard_scores
  for insert
  to anon, authenticated
  with check (
    char_length(player_name) between 1 and 20
    and score between 0 and 1000000
    and runs_completed between 0 and 5
    and outcome in ('flow_blocked', 'mission_complete')
  );

grant select, insert on table public.leaderboard_scores to anon, authenticated;
grant usage, select on sequence public.leaderboard_scores_id_seq to anon, authenticated;
